name: spectralDNS
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cython
  - h5py[build=mpi*]
  - mpi4py-fft
  - mpich
  - numba
  - numpy[version='<=2.2']
  - pip
  - python=3.12
  - pythran
  - shenfun
  - pip:
      - nodepy==1.0.1
